### ISSUE TITLE
Remove duplicate index in `index.yaml`

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/viur-cli#67]
If you insert an index into `index.yaml` which already exists there, the duplicate should be removed instead of sorting it twice in a row.

**Comment by Grashalmbeisser** [comment]
Can you elaborate this further somehow?

**Comment by sveneberth** [comment]
> Can you elaborate this further somehow?

Imagine this it the content of my `index.yaml`:
```yaml
indexes:

- kind: file
  properties:
  - name: weak
  - name: creationdate

- kind: file
  properties:
  - name: parententry
  - name: sortindex

# and many more entries
# ...
# ...
# ...
```

Now I add the index (which exist in the `index.yaml` already) at the end.
```yaml
- kind: file
  properties:
  - name: weak
  - name: creationdate
```


the `index.yaml` gets sorted
```yaml
indexes:

- kind: file
  properties:
  - name: weak
  - name: creationdate

- kind: file
  properties:
  - name: weak
  - name: creationdate

- kind: file
  properties:
  - name: parententry
  - name: sortindex

# and many more entries
# ...
# ...
# ...
```

Now I add the index
```yaml
- kind: file
  properties:
  - name: weak
  - name: creationdate
```
and contains the _"new"_ added index twice. But the `viur-cli` could detect the duplicate and eliminate it.
